language: python
# FIXME add printed openssl command from `travis encrypt-file travis-ci.key` here
before_install:
  - openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in travis-ci.key.enc -out travis-ci.key -d
install:
  - chmod 600 travis-ci.key
  - eval `ssh-agent -s`
  - ssh-add travis-ci.key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "nobody@travis.ci.org"
  # Re-attach HEAD
  - git checkout $TRAVIS_BRANCH
script:
  # TODO run stats update script
  - echo $TRAVIS_BUILD_NUMBER >> stats.json
after_success:
  - git commit -a --allow-empty -m "Updated stats by Travis-CI build $TRAVIS_BUILD_NUMBER"
  - git push git@github.com:${TRAVIS_REPO_SLUG}.git $TRAVIS_BRANCH
