baseurl: ''
created_at: 2015-10-02 12:46:14+00:00
description: 3D-e-Chem project of Netherlands eScience Center
excludes:
  - README.md
  - utils
markdown: kramdown
partners:
  - logo_url: https://www.esciencecenter.nl/img/pressroom/ESCIENCE_logo_C_nl_cyanblack.jpg
    url: https://www.esciencecenter.nl
# - logo_url: <FIXME AND OPTIONALLY REPEATME>
#   url: <FIXME AND OPTIONALLY REPEATME>
  - url: https://www.vu.nl
    logo_url: https://www.esciencecenter.nl/img/partners/VUlogo_EN_Wit_HR_RGB_tcm9-201385.png
  - url: https://www.radboudumc.nl
    logo_url: /assets/logo/Radboudumc.png
slug: 3D-e-Chem
title: 3D-e-Chem NLeSC project
urls:
  avatar: https://avatars.githubusercontent.com/u/14940717?v=3
  project: https://www.research-software.nl/projects/1091
  organization: https://github.com/3D-e-Chem
keep_files:
  - assets
  - updates
collections:
  repos:
    output: false
  team_members:
    output: true
    permalink: /team/:path/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: team_members
    values:
      layout: team
